#ifndef __HAL_UDMA_UDMA_DVSI_V1_H__
#define __HAL_UDMA_UDMA_DVSI_V1_H__

#include "archi/udma/dvsi/udma_dvsi_v1.h"

#define UDMA_DVSI_OFFSET 0x300

static inline void plp_dvsi_setup();

static inline void plp_dvsi_setup()
{
  pulp_write32(ARCHI_UDMA_ADDR + UDMA_DVSI_OFFSET + DVSI_CONTROL_OFFSET          , 0xFFFFFFFF);
  pulp_write32(ARCHI_UDMA_ADDR + UDMA_DVSI_OFFSET + DVSI_DST_OFFSET              , 0x000000FF);
  pulp_write32(ARCHI_UDMA_ADDR + UDMA_DVSI_OFFSET + DVSI_CROP_TOP_BOTTOM_OFFSET  , 0x00000000); // todo
  pulp_write32(ARCHI_UDMA_ADDR + UDMA_DVSI_OFFSET + DVSI_CROP_LEFT_RIGHT_OFFSET  , 0x00000000); // todo
  pulp_write32(ARCHI_UDMA_ADDR + UDMA_DVSI_OFFSET + DVSI_CFG_GLOB_OFFSET         , 0x00010136); // 0x00010196
  pulp_write32(ARCHI_UDMA_ADDR + UDMA_DVSI_OFFSET + DVSI_CFG_XYRES_OFFSET        , 0x00004D1D);
  pulp_write32(ARCHI_UDMA_ADDR + UDMA_DVSI_OFFSET + DVSI_CFG_TIMER_OFFSET        , 0x08FF008F);
  pulp_write32(ARCHI_UDMA_ADDR + UDMA_DVSI_OFFSET + DVSI_L2_START_ADDR_OFFSET    , 0x00000000);
  pulp_write32(ARCHI_UDMA_ADDR + UDMA_DVSI_OFFSET + DVSI_L2_ADDR_STEP_OFFSET     , 0x00000004);
  pulp_write32(ARCHI_UDMA_ADDR + UDMA_DVSI_OFFSET + DVSI_TRIGGER_THRESHOLD_OFFSET, 0x000000FF);
  pulp_write32(ARCHI_UDMA_ADDR + UDMA_DVSI_OFFSET + DVSI_TRIGGER_TDELTA_OFFSET   , 0x0000FFFF);
  pulp_write32(ARCHI_UDMA_ADDR + UDMA_DVSI_OFFSET + DVSI_INT_MODE_OFFSET         , 0x00000002);
  pulp_write32(ARCHI_UDMA_ADDR + UDMA_DVSI_OFFSET + DVSI_BIAS0_OFFSET            , 100000    );
  pulp_write32(ARCHI_UDMA_ADDR + UDMA_DVSI_OFFSET + DVSI_BIAS1_OFFSET            , 0x00000000);
  pulp_write32(ARCHI_UDMA_ADDR + UDMA_DVSI_OFFSET + DVSI_BIAS2_OFFSET            , 0x00000000);
  pulp_write32(ARCHI_UDMA_ADDR + UDMA_DVSI_OFFSET + DVSI_BIAS3_OFFSET            , 10000);
  pulp_write32(ARCHI_UDMA_ADDR + UDMA_DVSI_OFFSET + DVSI_BIAS4_OFFSET            , 400);
  pulp_write32(ARCHI_UDMA_ADDR + UDMA_DVSI_OFFSET + DVSI_BIAS5_OFFSET            , 10000);
  pulp_write32(ARCHI_UDMA_ADDR + UDMA_DVSI_OFFSET + DVSI_BIAS6_OFFSET            , 100000);
  pulp_write32(ARCHI_UDMA_ADDR + UDMA_DVSI_OFFSET + DVSI_BIAS7_OFFSET            , 100000);
  pulp_write32(ARCHI_UDMA_ADDR + UDMA_DVSI_OFFSET + DVSI_BIAS8_OFFSET            , 100000);
  pulp_write32(ARCHI_UDMA_ADDR + UDMA_DVSI_OFFSET + DVSI_BIAS9_OFFSET            , 10000);
  pulp_write32(ARCHI_UDMA_ADDR + UDMA_DVSI_OFFSET + DVSI_BIAS10_OFFSET           , 0x00000000);
  pulp_write32(ARCHI_UDMA_ADDR + UDMA_DVSI_OFFSET + DVSI_PARAMS_OFFSET           , 0x00000002);
  pulp_write32(ARCHI_UDMA_ADDR + UDMA_DVSI_OFFSET + DVSI_FB_CFG0_OFFSET          , 0x00000000);  // todo
  pulp_write32(ARCHI_UDMA_ADDR + UDMA_DVSI_OFFSET + DVSI_FB_CFG1_OFFSET          , 0x00000000);  // todo

}

#endif